### ISSUE TITLE
jdk11 generate WSDL error.(version 2.3.2)

### ISSUE THREAD

**Issue by wanghualiang** [eclipse-ee4j/metro-jax-ws#46]
i create a JDK11 java project.

```
package com.wanghl.service.impl;

import javax.jws.WebService;
import com.wanghl.service.FlashService;

@WebService(endpointInterface="com.wanghl.service.FlashService")
public class FlashServiceImpl implements FlashService {

	@Override
	public String sayHello(String userName) {
		return "hello!";
	}

}

package com.wanghl.service;

import javax.jws.WebResult;
import javax.jws.WebService;

@WebService(targetNamespace="http://webservice.arcflash.ca.com")
public interface FlashService {

	@WebResult(targetNamespace = "http://webservice.arcflash.ca.com")
	String sayHello( String userName);
}
```

but when i use jaxws-ri-2.3.2 to create WSDL. it always error. 
i have put my class under E:\jaxws-ri2.3.2\bin

on CMD.
E:\jaxws-ri2.3.2\bin>wsgen.bat -cp . com.wanghl.service.impl.FlashServiceImpl
error: compilation failed, errors should have been reported

there are no detail error. what should i do?

i confirm it work well in JAVA8 with version 2.3.2
but when i use java11. it will report this error.

**Comment by borjafg** [comment]
You should try run it again adding the param "-verbose" to get more info.

**Comment by smillidge** [comment]
JDK 11 isn't supported yet AFAIK

**Comment by lukasj** [comment]
@smillidge it is. So far I've found the only issue on JDK 11 which is going to be fixed by #53 

The error message here says that 'error: compilation failed', so it could be just that some class referenced from FlashServiceImpl is not on the classpath, but without seeing '-verbose' output, it hard to say what is going on

**Comment by lukasj** [comment]
feel free to reopen with more details if you can reproduce this with 2.3.3 and/or 3.0.0-M?
